@startuml forgot-password

!include style.puml 

|Usuário|
start

repeat
    :Inserir email;
    :Clicar em "Enviar código";

    if () then ([email válido])

        if () then ([email registrado])

            |Sistema|
            :Gerar código de recuperação;
            :Enviar email;

            |Usuário|

            repeat

                if () then ([reenviar código])
                    :Clicar em "Enviar novamente";

                    |Sistema|
                    :Gerar novo código de recuperação;
                    :Enviar email;

                    |Usuário|

                else ([continuar])
                endif

                :Digitar código;
                :Clicar em "Confirmar código";

                |Sistema|
                :Verificar código de recuperação;
            repeat while () is ([código inválido]) not ([código válido])

            |Usuário|
            repeat
                :Digitar nova senha;
                :Digitar confirmação de senha;
                :Clicar em "Confirmar nova senha";

                |Sistema|
                :Comparar senhas;
            repeat while () is ([não coincidem]) not ([coincidem])

            |Sistema|
            :Atualizar senha;

            |Usuário|
            :Exibir confirmação de sucesso;
            :Redirecionar para login;
            stop

        else ([email não encontrado])
        endif

    else ([email inválido])
    endif

    |Usuário|
    :Exibir erro;
    :Corrigir dados;

repeat while ()

@enduml